%STARTUP

%% add MATPOWER paths
addpath( ...
    'C:\Users\30678\Desktop\code\matlab\libs\matpower8.0\lib', ...
    'C:\Users\30678\Desktop\code\matlab\libs\matpower8.0\lib\t', ...
    'C:\Users\30678\Desktop\code\matlab\libs\matpower8.0\data', ...
    'C:\Users\30678\Desktop\code\matlab\libs\matpower8.0\most\lib', ...
    'C:\Users\30678\Desktop\code\matlab\libs\matpower8.0\most\lib\t', ...
    'C:\Users\30678\Desktop\code\matlab\libs\matpower8.0\mp-opt-model\lib', ...
    'C:\Users\30678\Desktop\code\matlab\libs\matpower8.0\mp-opt-model\lib\t', ...
    'C:\Users\30678\Desktop\code\matlab\libs\matpower8.0\mips\lib', ...
    'C:\Users\30678\Desktop\code\matlab\libs\matpower8.0\mips\lib\t', ...
    'C:\Users\30678\Desktop\code\matlab\libs\matpower8.0\mptest\lib', ...
    'C:\Users\30678\Desktop\code\matlab\libs\matpower8.0\mptest\lib\t', ...
    'C:\Users\30678\Desktop\code\matlab\libs\matpower8.0\extras\maxloadlim', ...
    'C:\Users\30678\Desktop\code\matlab\libs\matpower8.0\extras\maxloadlim\tests', ...
    'C:\Users\30678\Desktop\code\matlab\libs\matpower8.0\extras\maxloadlim\examples', ...
    'C:\Users\30678\Desktop\code\matlab\libs\matpower8.0\extras\misc', ...
    'C:\Users\30678\Desktop\code\matlab\libs\matpower8.0\extras\reduction', ...
    'C:\Users\30678\Desktop\code\matlab\libs\matpower8.0\extras\sdp_pf', ...
    'C:\Users\30678\Desktop\code\matlab\libs\matpower8.0\extras\se', ...
    'C:\Users\30678\Desktop\code\matlab\libs\matpower8.0\extras\simulink_matpower', ...
    'C:\Users\30678\Desktop\code\matlab\libs\matpower8.0\extras\simulink_matpower\helper_functions', ...
    'C:\Users\30678\Desktop\code\matlab\libs\matpower8.0\extras\simulink_matpower\helper_functions\getter_setter_functions', ...
    'C:\Users\30678\Desktop\code\matlab\libs\matpower8.0\extras\smartmarket', ...
    'C:\Users\30678\Desktop\code\matlab\libs\matpower8.0\extras\state_estimator', ...
    'C:\Users\30678\Desktop\code\matlab\libs\matpower8.0\extras\syngrid\lib', ...
    'C:\Users\30678\Desktop\code\matlab\libs\matpower8.0\extras\syngrid\lib\t', ...
    '-end' );
